trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/SimplyRecipes.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'appsettings.Production.json'
    displayName: "Download appsettings.Production.json"

- task: CopyFiles@2
  inputs:
    sourceFolder: "$(Agent.TempDirectory)"
    contents: "appsettings.Production.json"
    targetFolder: "$(Build.ArtifactStagingDirectory)"
  displayName: "Import Appsettings file"

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: Artifact
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'Simply Recipes'
