trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
- group: JsonVariableGroup
- name: buildConfiguration
  value: 'Release'
- name: Cloudinary.AppName
  value: '$(CloudinaryAppName)'
- name: Cloudinary.AppKey
  value: '$(CloudinaryAppKey)'
- name: Cloudinary.AppSecret
  value: '$(CloudinaryAppSecret)'

steps:
- task: FileTransform@1
  displayName: Tranform Appsettings
  inputs:
    folderPath: '**/*Tests/SimplyRecipes.Services.Data.Tests'
    fileType: 'json'
    targetFiles: 'appsettings.tests.json'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/SimplyRecipes.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: Artifact
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'Simply Recipes'
